application:
  ingress:
    host: maxdu.cis188.org
    secret_name: maxdu-cis188-org-tls

fastapi:
  image: ghcr.io/kevc528/aangs-stocks/web-app
  tag: fecd475a08a35e0714fe20c05126bab4b3085891
  port: 8000

cronjob:
  schedule: "*/1 * * * *"
