application:
  ingress:
    host: maxdu.cis188.org
    secret_name: maxdu-cis188-org-tls

fastapi:
  image: ghcr.io/kevc528/aangs-stocks/web-app
  tag: 8830377540e3d25c1f3e449e8df1e53e8364c8ce
  port: 8000

cronjob:
  schedule: "*/1 * * * *"
