application:
  ingress:
    host: maxdu.cis188.org
    secret_name: maxdu-cis188-org-tls

fastapi:
  image: ghcr.io/kevc528/aangs-stocks/web-app
  tag: 0ca91f60a517bfe8eee4f23a022feef0af545836
  port: 8000

cronjob:
  schedule: "*/1 * * * *"

environment:
  database_url: postgresql+psycopg2://postgres:postgres@postgres:5432
  email: your-email-address
  email_password: your-email-password
  jwt_secret: your-secret