application:
  ingress:
    host: maxdu.cis188.org
    secret_name: maxdu-cis188-org-tls

fastapi:
  image: ghcr.io/kevc528/aangs-stocks/web-app
  tag: d5e895c87b0497db0c05a96f7c9187401e120757
  port: 8000

cronjob:
  schedule: "*/1 * * * *"

environment:
  database_url: postgresql+psycopg2://postgres:postgres@postgres:5432
  email: aangstocks@gmail.com
  email_password: iloveaang
  jwt_secret: iloveaang