"""empty message

Revision ID: 785983b9b50d
Revises: f6829f6ef2f0
Create Date: 2021-04-23 03:06:11.596141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785983b9b50d'
down_revision = 'f6829f6ef2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
