"""empty message

Revision ID: 98b78d255050
Revises: e32032b447cb
Create Date: 2021-04-23 20:07:10.331487

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "98b78d255050"
down_revision = "e32032b447cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("current_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stocks", "current_price")
    # ### end Alembic commands ###
