"""empty message

Revision ID: e32032b447cb
Revises: 785983b9b50d
Create Date: 2021-04-23 03:18:46.854430

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e32032b447cb"
down_revision = "785983b9b50d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("mode", sa.String(length=4), nullable=True))
    op.drop_constraint("unique_stock", "stocks", type_="unique")
    op.create_unique_constraint("unique_stock", "stocks", ["ticker", "mode", "user_id"])
    op.drop_column("stocks", "buy")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("buy", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint("unique_stock", "stocks", type_="unique")
    op.create_unique_constraint("unique_stock", "stocks", ["ticker", "buy", "user_id"])
    op.drop_column("stocks", "mode")
    # ### end Alembic commands ###
