"""empty message

Revision ID: e85a73d0976e
Revises: 98b78d255050
Create Date: 2021-04-24 06:58:35.018587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85a73d0976e'
down_revision = '98b78d255050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
