"""empty message

Revision ID: f6829f6ef2f0
Revises: 24e17715ed8e
Create Date: 2021-04-22 22:54:10.073990

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f6829f6ef2f0"
down_revision = "24e17715ed8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("buy", sa.Boolean(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "buy", "user_id", name="unique_stock"),
    )
    op.create_index(op.f("ix_stocks_id"), "stocks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_id"), table_name="stocks")
    op.drop_table("stocks")
    # ### end Alembic commands ###
