apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-web-app
  name: {{ .Release.Name }}-web-app
spec:
  ports:
  - name: "8000"
    port: {{ .Values.fastapi.port }}
    targetPort: {{ .Values.fastapi.port }}
  selector:
    io.kompose.service: {{ .Release.Name }}-web-app
status:
  loadBalancer: {}
