apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web-app
    spec:
      containers:
      - args:
        - bash
        - -c
        - poetry run alembic upgrade head && poetry run uvicorn main:app --host 0.0.0.0
          --port 8000 --reload
        env:
        - name: DATABASE_URL
          value: postgresql+psycopg2://postgres:postgres@postgres:5432
        - name: EMAIL_ADDRESS
          value: aangstocks@gmail.com
        - name: EMAIL_PASSWORD
          value: iloveaang
        - name: JWT_SECRET
          value: iloveaang
        image: ghcr.io/kevc528/aangs-stocks/web-app:0ca91f60a517bfe8eee4f23a022feef0af545836
        imagePullPolicy: ""
        name: web-app
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
