# Default values for bender-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  ingress:
    host: None
    secret_name: None
    path: "/"

cronjob:
  schedule: "*/1 * * * *"

fastapi:
  image: None
  tag: None
  port: 8000
  replicas: 1

environment:
  database_url: postgresql+psycopg2://postgres:postgres@postgres:5432
  email: your-email
  email_password: your-password
  jwt_secret: your-secret