apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-emailer
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - bash
            - -c
            - poetry run python email_job.py
            env:
            - name: DATABASE_URL
              value: {{ .Values.environment.database_url }}
            - name: EMAIL_ADDRESS
              value: {{ .Values.environment.email }}
            - name: EMAIL_PASSWORD
              value: {{ .Values.environment.email_password }}
            image: "{{ .Values.fastapi.image }}:{{ .Values.fastapi.tag }}"
            imagePullPolicy: IfNotPresent
            name: worker
          imagePullSecrets:
            - name: docker-registry-registrycreds
          restartPolicy: OnFailure