apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-web-app
  name: {{ .Release.Name }}-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-web-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-web-app
    spec:
      containers:
      - args:
        - bash
        - -c
        - poetry run alembic upgrade head && poetry run uvicorn main:app --host 0.0.0.0
          --port 8000 --reload
        env:
        - name: DATABASE_URL
          value: {{ .Values.environment.database_url }}
        - name: EMAIL_ADDRESS
          value: {{ .Values.environment.email }}
        - name: EMAIL_PASSWORD
          value: {{ .Values.environment.email_password }}
        - name: JWT_SECRET
          value: {{ .Values.environment.jwt_secret }}
        image: "{{ .Values.fastapi.image }}:{{ .Values.fastapi.tag }}"
        imagePullPolicy: ""
        name: {{ .Release.Name }}-web-app
        ports:
        - containerPort: {{ .Values.fastapi.port }}
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
